### ISSUE TITLE
QSP-11 Shadowed Hooks

### ISSUE THREAD

**Issue by Agusx1211** [arcadeum/wallet-contracts#72]
<img width="1488" alt="Screenshot 2020-06-08 at 12 31 28" src="https://user-images.githubusercontent.com/12701942/84020935-fa196680-a983-11ea-9ba8-2c351404bdf3.png">

**Comment by PhABC** [comment]
This should pose no issues as this action would have to be deliberate and would cause no potential vulnerability. We can add a note on this in the documentation, that adding hooks for existing methods will not have any impact since the original function will be called and not the hook, as the tx will never reach the fallback() method.
